/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_other_jni_TestLib */

#ifndef _Included_org_example_other_jni_TestLib
#define _Included_org_example_other_jni_TestLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_other_jni_TestLib
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_other_jni_TestLib_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     org_example_other_jni_TestLib
 * Method:    getPid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_other_jni_TestLib_getPid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
